name: neurosync
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  audioplayers: 
  avatar_glow: ^2.0.2
  awesome_dialog: null
  awesome_dropdown: ^0.0.4
  barcode_widget: null
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.1.0
  camera: null
  carousel_slider: ^4.1.1
  clipboard: ^0.1.3
  cloud_firestore: null
  country_code_picker: ^3.0.0
  coupon_uikit: ^0.2.0
  crypto: null
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.4
  dynamic_height_grid_view: ^0.0.3
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  fancy_password_field: ^2.0.2
  favorite_button: ^0.0.4
  firebase_core: null
  firebase_core_platform_interface: ^5.0.0
  firebase_messaging: null
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_asset_generator: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_share: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: null
  flutter_zoom_drawer: ^3.0.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  gap: ^3.0.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  get: ^4.6.5
  get_it: ^7.6.7
  google_maps_flutter: ^2.2.6
  google_maps_webservice: 0.0.20-nullsafety.5
  image_cropper: null
  image_picker: ^1.0.4
  image_preview: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  intl: null
  local_auth: ^2.1.6
  location: ^5.0.3
  lottie: ^2.7.0
  multi_image_picker_view: null
  page_transition: ^2.0.7
  path_provider: ^2.0.14
  pdf: null
  percent_indicator: any
  photo_view: ^0.14.0
  pinput: ^3.0.1
  qr_flutter: null
  record: 4.4.4
  screen_size_test: ^1.0.2+3
  share_plus: null
  shared_preferences: ^2.0.13
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  speech_to_text: ^6.1.1
  status_change: ^2.0.0
  substring_highlight: ^1.0.33
  tflite_flutter: ^0.10.4
  timeago: null
  translator: ^0.1.7
  url_launcher: ^6.1.3
  voice_message_package: ^2.0.0
  webview_flutter: null
  flutter_onboarding_slider: ^1.0.11
  fast_contacts: ^3.1.3
  flutter_toggle_tab: ^1.4.1
  fl_chart :  0.67.0
  dyte_uikit: ^0.7.5
  # mindwave_mobile2: ^1.0.0+2


dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/
    - assets/models/
 # Inter lora fonts

  fonts:
    - family: LoraBold
      fonts:
        - asset: assets/fonts/Lora-Bold.ttf
    - family: LoraMedium
      fonts:
        - asset: assets/fonts/Lora-Medium.ttf
    - family: LoraRegular
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf

    - family: LoraSemiBold
      fonts:
        - asset: assets/fonts/Lora-SemiBold.ttf


 # Inter fonts
    - family: InterBlack
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
    - family: InterExtraLight
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf

    - family: InterBold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf



    - family: InterLight
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf     
        
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf                 

