// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPrmcPKMm21jqd1X4P4A1TqWoT-yOFo34',
    appId: '1:971361389695:web:d0181aa4bf6659cdff034a',
    messagingSenderId: '971361389695',
    projectId: 'ahhmed-adel',
    authDomain: 'ahhmed-adel.firebaseapp.com',
    storageBucket: 'ahhmed-adel.appspot.com',
    measurementId: 'G-DBG4WSP6C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZtlE9a66rEVg52sOxo11Fw-qeiCYLxQ',
    appId: '1:971361389695:android:419292b6d8003aa9ff034a',
    messagingSenderId: '971361389695',
    projectId: 'ahhmed-adel',
    storageBucket: 'ahhmed-adel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbM8v2XNF4UIqkQO7mfjzDHSCqDGkN2kw',
    appId: '1:971361389695:ios:a35aeef7bc4ea053ff034a',
    messagingSenderId: '971361389695',
    projectId: 'ahhmed-adel',
    storageBucket: 'ahhmed-adel.appspot.com',
    iosBundleId: 'com.samy.neurosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbM8v2XNF4UIqkQO7mfjzDHSCqDGkN2kw',
    appId: '1:971361389695:ios:f83716219804149dff034a',
    messagingSenderId: '971361389695',
    projectId: 'ahhmed-adel',
    storageBucket: 'ahhmed-adel.appspot.com',
    iosBundleId: 'com.samy.neurosync.RunnerTests',
  );
}
